name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
          check-latest: true
      
      - name: Build binaries
        run: |
          # Build for multiple platforms
          GOOS=linux GOARCH=amd64 go build -o prometheus-decoder-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o prometheus-decoder-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o prometheus-decoder-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o prometheus-decoder-windows-amd64.exe
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            prometheus-decoder-linux-amd64
            prometheus-decoder-darwin-amd64
            prometheus-decoder-darwin-arm64
            prometheus-decoder-windows-amd64.exe
          generate_release_notes: true
